### ISSUE TITLE
Invalid API-key, IP, or permissions for action

### ISSUE THREAD

**Issue by ciclanoio** [hackingthemarkets/supertrend-crypto-bot#6]
API is correct, I use in another BOT.  I recreate the API but receive the same error.

When the bot try create a new order.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\supertrend-crypto-bot\supertrend.py", line 29, in <module>
    print(exchange.fetch_balance().get('USDT').get('free'))
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\binance.py", line 1183, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\binance.py", line 3846, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\base\exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\binance.py", line 3840, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\supertrend-crypto-bot\venv\lib\site-packages\ccxt\base\exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binanceus {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Thanks for any help.

**Comment by ciclanoio** [comment]
Solved using code updated here

https://github.com/wpet/supertrend-crypto-bot

Thanks
