### ISSUE TITLE
pandas already installed but cannot import it or something like that

### ISSUE THREAD

**Issue by InfinityDOSS** [hackingthemarkets/supertrend-crypto-bot#8]
i dont know why this problem appear since i installed all requirements and insert the api key, i think the problem its pandas but i dont know what is the real problem.
Traceback (most recent call last):
  File "supertrend.py", line 4, in <module>
    import pandas as pd
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import (
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\compat\__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\compat\numpy\__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\util\__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
  File "pandas\_libs\hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "pandas\_libs\missing.pyx", line 1, in init pandas._libs.missing
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pandas\_libs\tslibs\__init__.py", line 31, in <module>
    from pandas._libs.tslibs.conversion import (
  File "pandas\_libs\tslibs\conversion.pyx", line 1, in init pandas._libs.tslibs.conversion
  File "pandas\_libs\tslibs\timezones.pyx", line 43, in init pandas._libs.tslibs.timezones
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\dateutil\tz\tz.py", line 1557, in __call__
    rv = self.nocache(name=name)
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\dateutil\tz\tz.py", line 1648, in nocache
    tz = tzwin(name)
  File "C:\Users\jeswd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\dateutil\tz\win.py", line 229, in __init__
    tup = struct.unpack("=3l16h", keydict["TZI"])
struct.error: unpack requires a buffer of 44 bytes

**Comment by simplevulnerabilitymanager** [comment]
Install python 3.10
